service: serverless-url-shortener

provider:
  name: aws
  endpointType: ${file(config.json):API_ENDPOINT_TYPE}
  runtime: nodejs8.10
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:${file(config.json):S3_PARTITION}:s3:::${file(config.json):BUCKET}/*"

functions:
  new:
    handler: lambda/new.handle
    events:
      - http:
          path: /new
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                url: true
                customAlias: false
  list:
    handler: lambda/list.handle
    events:
      - http:
          path: /list
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                marker: false
  search:
    handler: lambda/search.handle
    events:
      - http:
          path: /search
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                key: false
                url: false
  delete:
    handler: lambda/delete.handle
    events:
      - http:
          path: /delete
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                key: true
  edit:
    handler: lambda/edit.handle
    events:
      - http:
          path: /edit
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                key: true
                url: true

resources:
  Resources:
    
    ServerlesslyRedirectS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(config.json):BUCKET}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    
    ServerlesslyRedirectS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${file(config.json):BUCKET}
        PolicyDocument:
          Statement:
          - Action:
            - s3:GetObject
            Effect: Allow
            Resource:
            - arn:${file(config.json):S3_PARTITION}:s3:::${file(config.json):BUCKET}/*
            Principal: "*"
